"""Project data for the X TechVerse site.
Facts come from the live websites (checked 7 Oct 2026). Where a site was unreachable,
only what is certain (name, sector from the portfolio, screenshot) is used.
"""

U = "https://portfolio.xtechverse.com/wp-content/uploads/2025/10/"

PROJECTS = [
    dict(slug="ahram-scan", featured=True, live=True, kind="site", country="eg",
         name=dict(ar="مركز الأهرام للأشعة", en="Ahram Scan"),
         sector=dict(ar="أشعة وتحاليل طبية", en="Radiology and medical labs"),
         city=dict(ar="القاهرة والجيزة", en="Cairo and Giza"),
         langs=dict(ar="العربية", en="Arabic"),
         type=dict(ar="موقع خدمات طبية", en="Medical services website"),
         summary=dict(ar="موقع لمركز أشعة وتحاليل بخمسة فروع، يحجز منه المريض موعده ويستعلم عن نتيجته.",
                      en="A website for a radiology and lab centre with five branches, where patients book visits and look up results."),
         about=dict(ar="مركز الأهرام للأشعة مركز تشخيص طبي متخصص في الأشعة والتحاليل المعملية، وله خمسة فروع في القاهرة والجيزة.",
                    en="Ahram Scan is a diagnostic centre for radiology and laboratory testing, with five branches across Cairo and Giza."),
         pages=dict(ar=["الرئيسية", "من نحن", "الأشعة (13 خدمة)", "التحاليل", "المدونة", "حجز موعد", "الاستعلام عن النتائج", "تواصل معنا"],
                    en=["Home", "About", "Radiology (13 services)", "Lab tests", "Blog", "Book a visit", "Results lookup", "Contact"]),
         features=dict(ar=["حجز موعد أونلاين", "صفحة للاستعلام عن نتائج التحاليل", "الفروع الخمسة على الخريطة", "آراء المرضى", "صفحة لكل خدمة أشعة"],
                       en=["Online appointment booking", "Lab results lookup", "All five branches on the map", "Patient reviews", "A page for every radiology service"]),
         url="https://ahramscan.com/",
         img="%D8%A7%D9%84%D8%B1%D8%A6%D9%8A%D8%B3%D9%8A%D8%A9-AHRAM-SCAN-%D9%85%D8%B1%D9%83%D8%B2-%D8%A7%D9%84%D8%A3%D9%87%D8%B1%D8%A7%D9%85-%D9%84%D9%84%D8%A3%D8%B4%D8%B9%D8%A9-%D9%88%D8%A7%D9%84%D8%AA%D8%AD%D8%A7%D9%84%D9%8A%D9%84-10-18-2025_02_29_PM-scaled.webp"),
    dict(slug="cross-road", featured=True, live=True, kind="site", country="sa",
         name=dict(ar="Cross Road", en="Cross Road"),
         sector=dict(ar="وكالة تسويق", en="Marketing agency"),
         city=dict(ar="القاهرة والرياض", en="Cairo and Riyadh"),
         langs=dict(ar="العربية والإنجليزية", en="Arabic and English"),
         type=dict(ar="موقع شركة", en="Company website"),
         summary=dict(ar="موقع لوكالة تسويق متكاملة بمكتبين في القاهرة والرياض، يعرض خدماتها وأعمالها وفريقها.",
                      en="A website for a full-service marketing agency with offices in Cairo and Riyadh, showing its services, work and team."),
         about=dict(ar="Cross Road وكالة تسويق تقدم الاستراتيجية والحملات الرقمية والهوية البصرية والإنتاج والفعاليات والعلاقات العامة.",
                    en="Cross Road is a marketing agency covering strategy, digital campaigns, branding, production, events and PR."),
         pages=dict(ar=["الرئيسية", "من نحن", "العملاء", "المدونة", "تواصل معنا"], en=["Home", "About", "Clients", "Blog", "Contact"]),
         features=dict(ar=["معرض أعمال بتصنيفات", "شعارات أكثر من 15 عميل", "صفحة الفريق", "آراء العملاء", "المكتبين على الخريطة", "نسخة عربي وإنجليزي"],
                       en=["Filterable portfolio", "Logos of 15+ clients", "Team profiles", "Client testimonials", "Both offices on the map", "Arabic and English versions"]),
         url="https://crossroad-global.com/", img="Home-Cross-Road-10-18-2025_02_11_PM-scaled.webp"),
    dict(slug="sistema-plastic-egypt", featured=True, live=True, kind="store", country="eg",
         name=dict(ar="Sistema Plastic Egypt", en="Sistema Plastic Egypt"),
         sector=dict(ar="متجر أدوات مطبخ", en="Kitchenware store"),
         city=dict(ar="مصر", en="Egypt"),
         langs=dict(ar="العربية والإنجليزية", en="Arabic and English"),
         type=dict(ar="متجر إلكتروني", en="Online store"),
         summary=dict(ar="متجر إلكتروني لعبوات حفظ الطعام وزجاجات المياه من Sistema في مصر، بأكثر من 96 منتج.",
                      en="An online store for Sistema food containers and bottles in Egypt, with more than 96 products."),
         about=dict(ar="Sistema Plastic Egypt تبيع منتجات Sistema لحفظ الطعام وعلب الغداء وزجاجات المياه وتنظيم المطبخ في مصر.",
                    en="Sistema Plastic Egypt sells Sistema food storage, lunch boxes, bottles and kitchen organisers in Egypt."),
         pages=dict(ar=["الرئيسية", "Lunch box", "Hydration", "Microwave", "Klip It Plus", "Ultra", "Brilliance", "To Go", "من نحن", "تواصل معنا"],
                    en=["Home", "Lunch box", "Hydration", "Microwave", "Klip It Plus", "Ultra", "Brilliance", "To Go", "About", "Contact"]),
         features=dict(ar=["أكثر من 96 منتج في 8 أقسام", "سلة مشتريات", "حسابات للعملاء", "قائمة المفضلة", "مقارنة المنتجات", "عربي وإنجليزي"],
                       en=["96+ products in 8 categories", "Shopping cart", "Customer accounts", "Wishlist", "Product comparison", "Arabic and English"]),
         url="https://sistemaplasticegypt.com/", img="Sistema-Plastic-Egypt-10-18-2025_02_20_PM-scaled.webp"),
    dict(slug="ellwaa", featured=True, live=True, kind="site", country="eg",
         name=dict(ar="Ellwaa", en="Ellwaa"),
         sector=dict(ar="استشارات قانونية وتأسيس شركات", en="Legal consulting and company formation"),
         city=dict(ar="القاهرة والرياض", en="Cairo and Riyadh"),
         langs=dict(ar="الإنجليزية", en="English"),
         type=dict(ar="موقع شركة", en="Company website"),
         summary=dict(ar="موقع لمكتب استشارات قانونية وتأسيس شركات منذ 1989، فيه مقالات وبودكاست ومنصة لطلبات التأسيس.",
                      en="A website for a legal and company-formation firm founded in 1989, with articles, a podcast and a formation request platform."),
         about=dict(ar="Ellwaa مكتب متخصص في الحوكمة وهيكلة الشركات القابضة وتأسيس الشركات، ومكاتبه في القاهرة والرياض.",
                    en="Ellwaa works on corporate governance, holding structures and company formation, with offices in Cairo and Riyadh."),
         pages=dict(ar=["نظرة عامة", "العملاء", "المقالات", "الفريق", "الفعاليات", "الخدمات", "الوظائف", "المدونة", "تواصل معنا"],
                    en=["Overview", "Clients", "Insights", "People", "Events", "Services", "Careers", "Blog", "Contact"]),
         features=dict(ar=["منصة Assis لطلبات تأسيس الشركات", "بودكاست Ellwaa on Middle East", "مكتبة فيديو", "مدونة عن الضرائب والاستثمار في السعودية", "صفحات للفريق"],
                       en=["Assis platform for formation requests", "Ellwaa on Middle East podcast", "Video library", "Blog on Saudi tax and investment", "Team profiles"]),
         url="https://ellwaa.com/", img="%D8%A7%D9%84%D8%B1%D8%A6%D9%8A%D8%B3%D9%8A%D8%A9-Ellwaa-10-18-2025_02_13_PM-scaled.webp"),
    dict(slug="soft-light", featured=True, live=True, kind="site", country="sa", partner="Cross Road",
         name=dict(ar="Soft Light", en="Soft Light KSA"),
         sector=dict(ar="تنظيم حفلات ومعارض", en="Events and exhibitions"),
         city=dict(ar="الرياض", en="Riyadh"),
         langs=dict(ar="العربية والإنجليزية", en="Arabic and English"),
         type=dict(ar="موقع شركة", en="Company website"),
         summary=dict(ar="موقع لشركة تنظيم حفلات ومعارض ومؤتمرات وحلول إضاءة وصوت في السعودية.",
                      en="A website for a company that runs parties, exhibitions and conferences, with lighting and sound across Saudi Arabia."),
         about=dict(ar="Soft Light شركة في الرياض تنظّم الحفلات والمعارض والمؤتمرات، وتقدّم الخيام والإضاءة وأنظمة الصوت والضيافة.",
                    en="Soft Light is a Riyadh company organising parties, exhibitions and conferences, with tents, lighting, sound and catering."),
         pages=dict(ar=["الرئيسية", "من نحن", "الخدمات", "مشاريعنا", "المدونة", "تواصل معنا"], en=["Home", "About", "Services", "Projects", "Blog", "Contact"]),
         features=dict(ar=["معرض لمشاريع وفعاليات سابقة", "صفحات للخدمات", "أرقام الشركة", "تواصل بواتساب وتليفون وإيميل", "عربي وإنجليزي"],
                       en=["Gallery of past events", "Service pages", "Company figures", "WhatsApp, phone and email contact", "Arabic and English"]),
         url="https://softlightksa.com/",
         img="Soft-Light-KSA-%D8%B3%D9%88%D9%81%D8%AA-%D9%84%D8%A7%D9%8A%D8%AA-%D9%84%D8%AA%D9%86%D8%B8%D9%8A%D9%85-%D8%A7%D9%84%D8%AD%D9%81%D9%84%D8%A7%D8%AA-%D9%88-%D8%A7%D9%84%D9%85%D8%B9%D8%A7%D8%B1%D8%B6-%D9%88-%D8%A7%D9%84%D9%85%D9%86%D8%A7%D8%B3%D8%A8%D8%A7%D8%AA-10-18-2025_01_31_PM-scaled.webp"),
    dict(slug="excellence-event", featured=True, live=True, kind="site", country="sa", partner="Cross Road",
         name=dict(ar="تفوق الحدث", en="Excellence Event"),
         sector=dict(ar="أجنحة معارض ومسارح مؤتمرات", en="Exhibition stands and conference stages"),
         city=dict(ar="الرياض", en="Riyadh"),
         langs=dict(ar="العربية", en="Arabic"),
         type=dict(ar="موقع شركة", en="Company website"),
         summary=dict(ar="موقع لشركة تصميم وتنفيذ أجنحة المعارض ومسارح المؤتمرات في الرياض، بمعرض أعمال كبير.",
                      en="A website for a Riyadh company that designs and builds exhibition stands and conference stages, with a large work gallery."),
         about=dict(ar="تفوق الحدث شركة سعودية في الرياض متخصصة في تصميم وتنفيذ أجنحة المعارض ومسارح المؤتمرات والمطبوعات الدعائية.",
                    en="Excellence Event is a Riyadh company that designs and builds exhibition stands, conference stages and promotional print."),
         pages=dict(ar=["الرئيسية", "عن الشركة", "خدماتنا", "أعمالنا", "تواصل معنا"], en=["Home", "About", "Services", "Work", "Contact"]),
         features=dict(ar=["معرض بأكثر من 33 مشروع", "صفحات للخدمات", "تواصل مباشر بالتليفون والإيميل", "روابط السوشيال ميديا"],
                       en=["Gallery of 33+ projects", "Service pages", "Direct phone and email contact", "Social links"]),
         url="https://excellence-event.com/",
         img="%D8%B4%D8%B1%D9%83%D8%A9-%D8%AA%D9%81%D9%88%D9%82-%D8%A7%D9%84%D8%AD%D8%AF%D8%AB-10-18-2025_01_36_PM-scaled.webp"),
    dict(slug="efad", featured=False, live=True, kind="site", country="sa",
         name=dict(ar="إفاد", en="EFAD"),
         sector=dict(ar="استيراد وتصدير", en="Import and export"),
         city=dict(ar="السعودية والصين", en="Saudi Arabia and China"),
         langs=dict(ar="العربية والإنجليزية", en="Arabic and English"),
         type=dict(ar="موقع شركة", en="Company website"),
         summary=dict(ar="موقع لشركة استيراد وتصدير بين الصين والسعودية، من البحث عن المورد لحد التخليص الجمركي.",
                      en="A website for an import and export company between China and Saudi Arabia, from sourcing to customs clearance."),
         about=dict(ar="إفاد شركة استيراد وتصدير بمكاتب في الصين والسعودية، تقدم فحص الجودة والتغليف بعلامة العميل والشحن والتخليص.",
                    en="EFAD is an import and export company with offices in China and Saudi Arabia, offering inspection, private labelling, shipping and clearance."),
         pages=dict(ar=["الرئيسية", "من نحن", "الخدمات", "المقالات", "تواصل معنا"], en=["Home", "About", "Services", "Articles", "Contact"]),
         features=dict(ar=["عرض الخدمات خطوة بخطوة", "قسم مقالات", "عربي وإنجليزي"], en=["Step-by-step services", "Articles section", "Arabic and English"]),
         url="https://wp.rasmi.sa/efad/",
         img="%D8%A7%D9%81%D8%A7%D8%AF-EFAD-%E2%80%93-%D9%84%D9%84%D8%AA%D8%B5%D8%AF%D9%8A%D8%B1-%D9%88-%D8%A7%D9%84%D8%A5%D8%B3%D8%AA%D9%8A%D8%B1%D8%A7%D8%AF-10-18-2025_02_16_PM-scaled.webp"),
    dict(slug="building-eagles", featured=False, live=True, kind="site", country="sa",
         name=dict(ar="نسور المباني", en="Building Eagles"),
         sector=dict(ar="مقاولات عامة", en="General contracting"),
         city=dict(ar="السعودية", en="Saudi Arabia"),
         langs=dict(ar="العربية والإنجليزية", en="Arabic and English"),
         type=dict(ar="موقع شركة", en="Company website"),
         summary=dict(ar="موقع لشركة مقاولات وبناء سعودية بخبرة أكثر من 30 سنة.",
                      en="A website for a Saudi construction company with more than 30 years of experience."),
         about=dict(ar="نسور المباني شركة مقاولات عامة في السعودية، تقدم البناء والتصميم وإدارة المشاريع والترميم.",
                    en="Building Eagles is a Saudi general contractor covering construction, design, project management and renovation."),
         pages=None, features=dict(ar=["عربي وإنجليزي", "تهيئة للمشاركة على السوشيال ميديا"], en=["Arabic and English", "Social sharing previews"]),
         url="https://building-eagles.com/",
         img="Building-Eagles-%D9%86%D8%B3%D9%88%D8%B1-%D8%A7%D9%84%D9%85%D8%A8%D8%A7%D9%86%D9%8A-10-18-2025_02_06_PM-scaled.webp"),
    dict(slug="al-majd-al-bazigh", featured=False, live=True, kind="site", country="sa",
         name=dict(ar="المجد البازغ", en="Al Majd Al Bazigh"),
         sector=dict(ar="مجموعة شركات", en="Business group"),
         city=dict(ar="المدينة المنورة", en="Madinah"),
         langs=dict(ar="العربية والإنجليزية", en="Arabic and English"),
         type=dict(ar="موقع شركة", en="Company website"),
         summary=dict(ar="موقع لمجموعة سعودية تعمل في الاستيراد والتصدير والمقاولات وإنتاج الدواجن والسياحة.",
                      en="A website for a Saudi group working in import and export, contracting, poultry and tourism."),
         about=dict(ar="المجد البازغ مجموعة في المدينة المنورة بأربعة قطاعات: المقاولات، الاستيراد والتصدير، الدواجن والأغذية، والسياحة والضيافة.",
                    en="Al Majd Al Bazigh is a Madinah group with four sectors: contracting, import and export, poultry and food, and tourism."),
         pages=dict(ar=["الرئيسية", "من نحن", "الخدمات", "المدونة", "تواصل معنا"], en=["Home", "About", "Services", "Blog", "Contact"]),
         features=dict(ar=["صفحة لكل قطاع من الأربعة", "معرض بأكثر من 70 صورة مشاريع", "عربي وإنجليزي"], en=["A page for each of the four sectors", "Gallery of 70+ project photos", "Arabic and English"]),
         url="https://almajd-albazigh.com/", img="Home-Al-Majd-Al-Bazigh-10-18-2025_02_00_PM-scaled.webp"),
    dict(slug="three-points", featured=False, live=True, kind="site", country="sa",
         name=dict(ar="Three Points", en="Three Points"),
         sector=dict(ar="فندق", en="Hotel"),
         city=dict(ar="جدة", en="Jeddah"),
         langs=dict(ar="الإنجليزية", en="English"),
         type=dict(ar="موقع فندق", en="Hotel website"),
         summary=dict(ar="موقع لفندق في جدة يعرض الغرف والمطعم والسبا والمرافق.",
                      en="A website for a Jeddah hotel presenting its rooms, restaurant, spa and facilities."),
         about=dict(ar="Three Points فندق في جدة فيه أربعة أنواع غرف ومطعم وسبا وحمامات سباحة داخلية وخارجية.",
                    en="Three Points is a Jeddah hotel with four room types, a restaurant, a spa and indoor and outdoor pools."),
         pages=dict(ar=["الرئيسية", "عن الفندق", "الغرف", "المدونة", "تواصل معنا"], en=["Home", "About", "Rooms", "Blog", "Contact"]),
         features=dict(ar=["صفحة للغرف بأنواعها الأربعة", "عرض المطعم والسبا والمرافق"], en=["Rooms page with four room types", "Restaurant, spa and facilities"]),
         url="https://three-points-sa.com/", img="Three-Points-10-18-2025_02_00_PM-scaled.webp"),
    dict(slug="trust-move", featured=False, live=True, kind="site", country="sa",
         name=dict(ar="Trust Move", en="Trust Move"),
         sector=dict(ar="نقل معدات ثقيلة", en="Heavy equipment transport"),
         city=dict(ar="الظهران", en="Dhahran"),
         langs=dict(ar="الإنجليزية", en="English"),
         type=dict(ar="موقع شركة", en="Company website"),
         summary=dict(ar="موقع لشركة نقل معدات ثقيلة ومقاولات عامة في الظهران، فيه نموذج لطلب عرض سعر.",
                      en="A website for a heavy-haul and contracting company in Dhahran, with a quote request form."),
         about=dict(ar="Trust Move شركة سعودية في الظهران متخصصة في نقل المعدات الثقيلة بالسطحات والمقاولات العامة.",
                    en="Trust Move is a Dhahran company specialising in flatbed heavy-equipment transport and general contracting."),
         pages=dict(ar=["الرئيسية", "من نحن", "المدونة", "تواصل معنا"], en=["Home", "About", "Blog", "Contact"]),
         features=dict(ar=["نموذج طلب عرض سعر", "آراء العملاء وشعاراتهم"], en=["Quote request form", "Client testimonials and logos"]),
         url="https://trustmove-ksa.com/", img="Trust-Move-10-18-2025_02_07_PM-scaled.webp"),
    dict(slug="jeto", featured=False, live=False, kind="site", country="sa", partner="Cross Road",
         name=dict(ar="جتو", en="Jeto KSA"), sector=dict(ar="أنظمة سلامة", en="Safety systems"),
         city=dict(ar="السعودية", en="Saudi Arabia"), langs=None, type=dict(ar="موقع شركة", en="Company website"),
         summary=dict(ar="موقع لشركة أنظمة سلامة في السعودية.", en="A website for a Saudi safety systems company."),
         about=None, pages=None, features=None, url=None,
         img="%D8%B4%D8%B1%D9%83%D8%A9-%D8%AC%D8%AA%D9%80%D9%80%D9%80%D9%80%D9%88-Jeto-Co-10-18-2025_02_06_PM-scaled.webp"),
    dict(slug="shumou-abha", featured=False, live=False, kind="site", country="sa", partner="Cross Road",
         name=dict(ar="شموع أبها", en="Shumou Abha"), sector=dict(ar="موقع شركة", en="Company website"),
         city=dict(ar="أبها", en="Abha"), langs=None, type=dict(ar="موقع شركة", en="Company website"),
         summary=dict(ar="موقع لشركة شموع أبها في السعودية.", en="A website for Shumou Abha in Saudi Arabia."),
         about=None, pages=None, features=None, url=None, img="Shumouabha-10-18-2025_01_59_PM-scaled.webp"),
    dict(slug="beauty-secret", featured=False, live=False, kind="store", country="eg",
         name=dict(ar="Beauty Secret", en="Beauty Secret"), sector=dict(ar="مستحضرات تجميل", en="Beauty products"),
         city=dict(ar="مصر", en="Egypt"), langs=None, type=dict(ar="متجر إلكتروني", en="Online store"),
         summary=dict(ar="متجر إلكتروني لمستحضرات التجميل.", en="An online store for beauty products."),
         about=None, pages=None, features=None, url=None, img="Home-beauty-secret-store-10-18-2025_02_25_PM-scaled.webp"),
    dict(slug="hace", featured=False, live=False, kind="site", country="eg",
         name=dict(ar="HACE", en="HACE"), sector=dict(ar="معرض للفنادق", en="Hotel expo"),
         city=dict(ar="مصر", en="Egypt"), langs=None, type=dict(ar="موقع معرض", en="Expo website"),
         summary=dict(ar="موقع لمعرض متخصص في قطاع الفنادق.", en="A website for a hotel-industry expo."),
         about=None, pages=None, features=None, url=None, img="HACE-%E2%80%93-HOTEL-EXPO-10-18-2025_02_23_PM-scaled.webp"),
    dict(slug="zahra-housewares", featured=False, live=False, kind="store", country="eg",
         name=dict(ar="زهرة للأدوات المنزلية", en="Zahra Housewares"), sector=dict(ar="أدوات منزلية", en="Housewares"),
         city=dict(ar="مصر", en="Egypt"), langs=None, type=dict(ar="موقع شركة", en="Company website"),
         summary=dict(ar="موقع لشركة أدوات منزلية.", en="A website for a housewares company."),
         about=None, pages=None, features=None, url=None,
         img="%D8%A7%D9%84%D8%B1%D8%A6%D9%8A%D8%B3%D9%8A%D8%A9-Zahra-House-Wares-10-18-2025_02_19_PM-scaled.webp"),
    dict(slug="al-rayan", featured=False, live=False, kind="site", country="eg",
         name=dict(ar="الريان", en="Al Rayan"), sector=dict(ar="مكافحة حشرات", en="Pest control"),
         city=dict(ar="مصر", en="Egypt"), langs=None, type=dict(ar="موقع شركة", en="Company website"),
         summary=dict(ar="موقع لشركة مكافحة حشرات.", en="A website for a pest control company."),
         about=None, pages=None, features=None, url=None,
         img="%D8%B4%D8%B1%D9%83%D8%A9-%D8%A7%D9%84%D8%B1%D9%8A%D8%A7%D9%86-%D9%84%D9%85%D9%83%D8%A7%D9%81%D8%AD%D8%A9-%D8%A7%D9%84%D8%AD%D8%B4%D8%B1%D8%A7%D8%AA-%D9%85%D9%83%D8%A7%D9%81%D8%AD%D8%A9-%D8%B0%D9%83%D9%8A%D8%A9%E2%80%A6-%D9%84%D8%A8%D9%8A%D8%A6%D8%A9-%D8%B5%D8%AD%D9%8A%D8%A9-10-18-2025_02_15_PM-scaled.webp"),
    dict(slug="innovation-capital", featured=False, live=False, kind="site", country="sa",
         name=dict(ar="Innovation Capital", en="Innovation Capital"), sector=dict(ar="موقع شركة", en="Company website"),
         city=dict(ar="السعودية", en="Saudi Arabia"), langs=None, type=dict(ar="موقع شركة", en="Company website"),
         summary=dict(ar="موقع لشركة Innovation Capital.", en="A website for Innovation Capital."),
         about=None, pages=None, features=None, url=None, img="Inno-Capital-10-18-2025_02_01_PM-scaled.webp"),
]

APPS = [
    dict(slug="aqary-eg", name=dict(ar="عقاري EG", en="Aqary EG"),
         sector=dict(ar="عقارات", en="Real estate"), status=dict(ar="منشور على جوجل بلاي", en="Live on Google Play"),
         summary=dict(ar="تطبيق أندرويد يجمع الوحدات العقارية للبيع والإيجار، بخريطة وصفحة لكل وحدة وتواصل مباشر.",
                      en="An Android app that gathers property listings for sale and rent, with a map, a page per unit and direct contact."),
         url="https://play.google.com/store/apps/details?id=com.aqaryeg.xtechverse"),
    dict(slug="supermarket", name=dict(ar="سيستم سوبر ماركت", en="Supermarket system"),
         sector=dict(ar="تجزئة وتوصيل", en="Retail and delivery"), status=dict(ar="اتسلّم للعميل", en="Delivered"),
         summary=dict(ar="تطبيق للعميل، وتطبيق للمندوب، ولوحة تحكم للمحل فيها المنتجات والأوردرات والتقارير.",
                      en="A customer app, a driver app, and a store dashboard for products, orders and reports."), url=None),
    dict(slug="clinicawy", name=dict(ar="كلينيكاوي", en="Clinicawy"),
         sector=dict(ar="إدارة عيادات", en="Clinic management"), status=dict(ar="تحت التطوير", en="In development"),
         summary=dict(ar="نظام لإدارة العيادات: المواعيد، ملفات المرضى، الروشتات، والفواتير.",
                      en="Clinic management: appointments, patient files, prescriptions and invoices."), url=None),
]
