"""Service pages. Copy describes what X TechVerse offers; related projects point to real, checked work."""

SERVICES = [
 dict(slug="websites", icon="site", related=["cross-road", "ellwaa", "soft-light", "excellence-event", "efad", "al-majd-al-bazigh"],
  ar=dict(name="تصميم مواقع الشركات", short="مواقع تعريفية بالعربية والإنجليزية، سريعة وسهلة التعديل.",
   title="تصميم وبرمجة مواقع الشركات في مصر والسعودية | X TechVerse",
   desc="نصمم ونبرمج مواقع الشركات بالعربية والإنجليزية: صفحات خدمات، معرض أعمال، نماذج تواصل، وتهيئة لمحركات البحث. أعمال منشورة لشركات في القاهرة والرياض وجدة.",
   h1="تصميم وبرمجة مواقع الشركات", lead="موقع يشرح شركتك بوضوح، يظهر في نتائج البحث، ويحوّل الزائر إلى عميل يتواصل معك.",
   intro="الموقع هو أول مكان يتحقق منه العميل قبل أن يتواصل معك. نبني مواقع الشركات من الصفر بتصميم خاص بهويتك، بالعربية والإنجليزية، ونجهزها لتظهر في جوجل وتعمل بسرعة على الموبايل.",
   incl=[("تصميم خاص بهويتك","لا قوالب جاهزة؛ نصمم الصفحات حول نشاطك وجمهورك."),("عربي وإنجليزي","نسختان كاملتان مع اتجاه صحيح لكل لغة."),
         ("صفحات الخدمات والأعمال","صفحة لكل خدمة ومعرض لمشاريعك السابقة."),("نماذج تواصل وطلب عروض","تصل الطلبات إلى بريدك وواتساب."),
         ("تهيئة لمحركات البحث","عناوين ووصف وبيانات منظمة وخريطة موقع."),("لوحة تحكم سهلة","تعدّل النصوص والصور والمشاريع بنفسك.")],
   who="شركات المقاولات، الوكالات، المكاتب الاستشارية، الفنادق، شركات الفعاليات، والاستيراد والتصدير.",
   faqs=[("هل يمكنني تعديل محتوى الموقع بنفسي؟","نعم، نسلّمك لوحة تحكم تعدّل منها النصوص والصور والمشاريع، ونشرح لك طريقة استخدامها."),
         ("هل الموقع يظهر في جوجل؟","نجهز الموقع تقنياً لمحركات البحث من البداية: عناوين ووصف لكل صفحة، وروابط واضحة، وخريطة موقع، وسرعة تحميل جيدة.")]),
  en=dict(name="Company websites", short="Arabic and English websites that are fast and easy to update.",
   title="Company website design and development in Egypt and Saudi Arabia | X TechVerse",
   desc="We design and build company websites in Arabic and English: service pages, portfolios, contact forms and search engine setup. Live work for companies in Cairo, Riyadh and Jeddah.",
   h1="Company website design and development", lead="A website that explains your company clearly, shows up in search, and turns visitors into enquiries.",
   intro="Your website is the first place a client checks before contacting you. We build company websites from scratch around your brand, in Arabic and English, ready for Google and fast on mobile.",
   incl=[("Designed for your brand","No ready-made templates; pages are designed around your business and audience."),("Arabic and English","Two complete versions with the right direction for each language."),
         ("Service and portfolio pages","A page for every service and a gallery of your past projects."),("Contact and quote forms","Enquiries reach your inbox and WhatsApp."),
         ("Search engine setup","Titles, descriptions, structured data and a sitemap."),("Easy admin panel","Edit text, images and projects yourself.")],
   who="Contractors, agencies, consultancies, hotels, event companies and import/export businesses.",
   faqs=[("Can I edit the website content myself?","Yes. You get an admin panel to edit text, images and projects, and we show you how to use it."),
         ("Will the website show up on Google?","We prepare it for search from day one: titles and descriptions per page, clean links, a sitemap and fast loading.")])),
 dict(slug="online-stores", icon="store", related=["sistema-plastic-egypt"],
  ar=dict(name="المتاجر الإلكترونية", short="متاجر بكتالوج وسلة وحسابات للعملاء.",
   title="إنشاء متجر إلكتروني في مصر والسعودية | X TechVerse",
   desc="نبني متاجر إلكترونية بالعربية والإنجليزية: كتالوج منتجات وأقسام، سلة مشتريات، حسابات عملاء، مفضلة ومقارنة، وربط بوسائل الدفع والشحن.",
   h1="إنشاء المتاجر الإلكترونية", lead="متجر منظم يعرض منتجاتك بوضوح ويسهّل على العميل الطلب من الموبايل.",
   intro="نبني متاجر جاهزة للبيع: أقسام ومنتجات بصور وتفاصيل، سلة مشتريات، وحسابات للعملاء. ونجهزها باللغتين لتخدم السوق المصري والخليجي.",
   incl=[("كتالوج وأقسام","أقسام ومنتجات بلا حدود مع صور ومواصفات."),("سلة وطلبات","سلة مشتريات وصفحة متابعة للطلب."),("حسابات العملاء","تسجيل دخول وسجل طلبات وقائمة مفضلة."),
         ("مقارنة المنتجات","يقارن العميل بين المنتجات قبل الشراء."),("الدفع والشحن","ربط بوسائل الدفع وشركات الشحن المتاحة لك."),("عربي وإنجليزي","نسختان كاملتان للمتجر.")],
   who="العلامات التجارية، الموزعون، ومحلات التجزئة التي تريد البيع أونلاين.",
   faqs=[("هل أستطيع إضافة المنتجات بنفسي؟","نعم، من لوحة تحكم المتجر تضيف المنتجات والأسعار والصور والعروض."),
         ("ما وسائل الدفع المتاحة؟","نربط المتجر بوسائل الدفع المتاحة لنشاطك في مصر أو السعودية، ونحددها معك في البداية.")]),
  en=dict(name="Online stores", short="Stores with catalogue, cart and customer accounts.",
   title="Online store development in Egypt and Saudi Arabia | X TechVerse",
   desc="We build online stores in Arabic and English: product catalogue and categories, cart, customer accounts, wishlist and compare, with payment and shipping integration.",
   h1="Online store development", lead="An organised store that presents your products clearly and makes ordering easy on mobile.",
   intro="We build stores that are ready to sell: categories and products with photos and details, a cart and customer accounts, in both languages for the Egyptian and Gulf markets.",
   incl=[("Catalogue and categories","Unlimited categories and products with photos and specs."),("Cart and orders","A cart and an order tracking page."),("Customer accounts","Login, order history and wishlist."),
         ("Product comparison","Customers compare products before buying."),("Payment and shipping","Integration with the payment and shipping options available to you."),("Arabic and English","Two complete versions of the store.")],
   who="Brands, distributors and retailers that want to sell online.",
   faqs=[("Can I add products myself?","Yes. From the store admin you add products, prices, photos and offers."),
         ("Which payment methods are available?","We connect the payment options available to your business in Egypt or Saudi Arabia and agree on them at the start.")])),
 dict(slug="mobile-apps", icon="app", related=[], apps=True,
  ar=dict(name="تطبيقات الموبايل", short="تطبيقات أندرويد وiOS من التصميم حتى النشر على المتاجر.",
   title="تصميم وبرمجة تطبيقات الموبايل | X TechVerse",
   desc="نصمم ونبرمج تطبيقات أندرويد وiOS: تصميم الواجهات، الخرائط، الإشعارات، لوحات التحكم، والنشر على جوجل بلاي. من أعمالنا تطبيق عقاري EG وسيستم سوبر ماركت.",
   h1="تصميم وبرمجة تطبيقات الموبايل", lead="تطبيق يخدم عملاءك أو فريقك يومياً، من أول شاشة حتى النشر على المتجر.",
   intro="نبني التطبيق كاملاً: نصمم الشاشات ونراجعها معك، نبرمج التطبيق ولوحة التحكم التي تديره منها، ثم ننشره على المتجر ونتابع معك بعد الإطلاق.",
   incl=[("تصميم الواجهات","شاشات واضحة ومريحة تراجعها قبل البرمجة."),("أندرويد وiOS","تطبيق يعمل على النظامين."),("الخرائط والموقع","عرض الأماكن والعناوين والتتبع على الخريطة."),
         ("الإشعارات","تنبيهات للعميل عند كل تحديث مهم."),("لوحة تحكم","تدير منها المحتوى والطلبات والمستخدمين."),("النشر على المتاجر","نجهز التطبيق وننشره على جوجل بلاي.")],
   who="العقارات، المتاجر والسوبر ماركت، العيادات، وأي نشاط يخدم عملاءه يومياً.",
   faqs=[("هل التطبيق يحتاج لوحة تحكم؟","غالباً نعم؛ نبني لوحة تحكم تدير منها المحتوى والطلبات بدون الرجوع إلينا."),
         ("هل تنشرون التطبيق على المتجر؟","نعم، نجهز التطبيق وننشره، كما فعلنا مع عقاري EG على جوجل بلاي.")]),
  en=dict(name="Mobile apps", short="Android and iOS apps, from design to store release.",
   title="Mobile app design and development | X TechVerse",
   desc="We design and build Android and iOS apps: interface design, maps, notifications, admin dashboards and Google Play release. Our work includes the Aqary EG app and a supermarket system.",
   h1="Mobile app design and development", lead="An app that serves your customers or your team every day, from the first screen to the store release.",
   intro="We build the whole app: we design the screens and review them with you, build the app and the dashboard you run it from, then publish it and stay with you after launch.",
   incl=[("Interface design","Clear screens you review before any code."),("Android and iOS","One app on both platforms."),("Maps and location","Places, addresses and tracking on a map."),
         ("Notifications","Alerts for every important update."),("Admin dashboard","Manage content, orders and users."),("Store release","We prepare and publish the app on Google Play.")],
   who="Real estate, stores and supermarkets, clinics, and any business that serves customers daily.",
   faqs=[("Does the app need a dashboard?","Usually yes; we build one so you manage content and orders without coming back to us."),
         ("Do you publish the app on the store?","Yes. We prepare and publish it, as we did with Aqary EG on Google Play.")])),
 dict(slug="custom-systems", icon="sys", related=[], apps=True,
  ar=dict(name="الأنظمة المخصصة والصيانة", short="لوحات تحكم وأنظمة إدارة، وصيانة للمواقع القائمة.",
   title="برمجة أنظمة إدارة مخصصة وصيانة المواقع | X TechVerse",
   desc="نبرمج أنظمة إدارة مخصصة مثل أنظمة العيادات والمتاجر، ونقدم صيانة شهرية للمواقع: تحديثات، حماية، نسخ احتياطي، وتحسين السرعة.",
   h1="الأنظمة المخصصة وصيانة المواقع", lead="نظام مبني على طريقة شغلك، وموقع يبقى محدثاً وآمناً وسريعاً.",
   intro="عندما لا يناسبك برنامج جاهز، نبني لك نظاماً على مقاس شغلك: مواعيد، مخزون، طلبات، تقارير. ولمواقعك القائمة نقدم صيانة مستمرة تحميها وتحافظ على سرعتها.",
   incl=[("أنظمة إدارة","عيادات، متاجر، توصيل، أو أي سير عمل داخلي."),("تقارير ولوحات بيانات","أرقام شغلك أمامك في مكان واحد."),("صلاحيات المستخدمين","كل موظف يرى ما يخصه فقط."),
         ("تحديثات وحماية","تحديث المنصة والإضافات وحماية من الاختراق."),("نسخ احتياطي","نسخ منتظمة لموقعك وبياناتك."),("تحسين السرعة","ضغط الصور وضبط الكاش وتنظيف الإضافات.")],
   who="العيادات، المتاجر، شركات التوصيل، وأصحاب المواقع القائمة.",
   faqs=[("هل يمكن ربط النظام بالموقع أو التطبيق؟","نعم، نصمم النظام ليعمل مع موقعك أو تطبيقك ويشاركهم نفس البيانات."),
         ("ماذا تشمل الصيانة الشهرية؟","تحديثات المنصة والإضافات، الحماية، النسخ الاحتياطي، ومتابعة أن الموقع يعمل، ونتفق على التفاصيل حسب موقعك.")]),
  en=dict(name="Custom systems and care", short="Dashboards and management systems, plus care for existing sites.",
   title="Custom management systems and website maintenance | X TechVerse",
   desc="We build custom management systems such as clinic and store systems, and offer monthly website care: updates, security, backups and speed work.",
   h1="Custom systems and website care", lead="A system built around how you work, and a website that stays updated, secure and fast.",
   intro="When off-the-shelf software does not fit, we build a system around your workflow: appointments, stock, orders, reports. For existing sites we provide ongoing care that keeps them safe and fast.",
   incl=[("Management systems","Clinics, stores, delivery or any internal workflow."),("Reports and dashboards","Your business numbers in one place."),("User permissions","Each employee sees only what they need."),
         ("Updates and security","Platform and plugin updates and protection."),("Backups","Regular backups of your site and data."),("Speed work","Image compression, caching and plugin clean-up.")],
   who="Clinics, stores, delivery companies and owners of existing websites.",
   faqs=[("Can the system connect to my website or app?","Yes. We design it to work with your site or app and share the same data."),
         ("What does monthly care include?","Platform and plugin updates, security, backups and uptime checks, agreed per site.")])),
]
